### ISSUE TITLE
Batch query: Keep uploaded file with list of coordinates to search

### ISSUE THREAD

**Issue by cacereslab** [caceres-lab/InvFEST-code#26]
The file with the list of inversions dissapears every time a search is performed and you need to uploaded again every time if you want to modify the search parameters

**Comment by RuthGG** [comment]
I have added a checkbox option (checked by default) that allows the user to run another search with the same file. The checkbox overrides the file upload, so it has the be unchecked in order to take into account a new file, even if it has been already selected with the 'Choose file' button. 

![image](https://user-images.githubusercontent.com/22767844/37517287-2db9bdf0-2911-11e8-8cae-ebd9292f640d.png)
